POST http://localhost:8080/api/books
Content-Type: application/json

{
  "name":"newOne",
  "price": 400
}

####

PUT http://localhost:8080/api/books
Content-Type: application/json

{
  "id": 10,
  "name":"Mu-dsf",
  "price": 2000
}

####

POST http://localhost:8080/api/sign-up
Content-Type: application/json

{
  "name":"Zhakhongir",
  "password":"qwerty007",
  "status":2
}
####

POST http://localhost:8080/api/sign-in
Content-Type: application/json

{
  "name":"Zhakhongir",
  "password":"qwerty007"
}

###

GET http://localhost:8080/api/books/15
Content-Type: application/json
Jwt: eydfsnjksdfiu342rnj23nr4kjn.32rnjkndsjfhnuihnk
sdf: dsfsdf
